# Default configuration for Uncertainty-Aware Intrusion Detection System

# Model Configuration
model:
  type: "bayesian_ensemble"  # Options: bayesian_ensemble, single_transformer
  ensemble_size: 10
  d_model: 128
  max_seq_len: 50
  n_classes: 2
  dropout_rate: 0.1
  diversity_factor: 0.1

# Data Configuration
data:
  sequence_length: 50
  normalize_method: "standard"  # Options: standard, minmax, robust
  target_column: "label"
  dataset_type: "auto"  # Options: auto, nsl-kdd, cicids2017, unsw-nb15, generic
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  batch_size: 64
  num_workers: 4
  shuffle: true

# Training Configuration
training:
  n_epochs: 100
  learning_rate: 0.001
  weight_decay: 0.00001
  optimizer: "adam"  # Options: adam, adamw, sgd
  scheduler: "reduce_on_plateau"  # Options: reduce_on_plateau, cosine, step, none
  scheduler_params:
    mode: "min"
    factor: 0.5
    patience: 10
    verbose: true
  gradient_clip_norm: 1.0
  
  # Regularization
  ensemble_diversity_weight: 0.01
  uncertainty_regularization_weight: 0.01
  
  # Early stopping
  early_stopping_patience: 20
  early_stopping_min_delta: 0.0001
  
  # Logging and validation
  log_every: 10
  validate_every: 1
  
  # Device
  device: "auto"  # Options: auto, cpu, cuda, mps

# Checkpointing
checkpointing:
  save_best_model: true
  save_checkpoint_every: 10
  checkpoint_dir: "./checkpoints"

# Uncertainty Calibration
calibration:
  enable: true
  method: "temperature"  # Options: temperature, platt, isotonic
  uncertainty_threshold: 0.2

# Evaluation
evaluation:
  metrics:
    - "accuracy"
    - "precision" 
    - "recall"
    - "f1_score"
    - "auc_roc"
    - "auc_pr"
    - "false_positive_rate"
    - "expected_calibration_error"
    - "uncertainty_accuracy_correlation"
  
  uncertainty_evaluation: true
  calibration_evaluation: true
  generate_plots: true
  save_predictions: true

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  reload: false
  log_level: "info"
  
  # Request limits
  max_request_size: 10485760  # 10MB
  request_timeout: 30
  
  # Monitoring
  enable_metrics: true
  metrics_window_size: 1000
  
  # Health checks
  health_check_interval: 30
  
  # CORS
  cors_origins: ["*"]
  cors_methods: ["GET", "POST"]
  cors_headers: ["*"]

# Logging Configuration
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_logging: false
  log_file: "uncertainty_ids.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5

# Paths
paths:
  data_dir: "./data"
  output_dir: "./outputs"
  model_dir: "./models"
  preprocessor_dir: "./preprocessors"
  logs_dir: "./logs"

# Reproducibility
reproducibility:
  seed: 42
  deterministic: false  # Set to true for full reproducibility (may impact performance)

# Performance
performance:
  mixed_precision: false  # Enable for faster training on compatible hardware
  compile_model: false    # Enable PyTorch 2.0 model compilation
  
# Monitoring and Alerting
monitoring:
  enable: true
  
  # Alert thresholds
  alerts:
    high_attack_rate_threshold: 0.5
    high_uncertainty_rate_threshold: 0.3
    low_confidence_threshold: 0.6
    high_memory_usage_threshold: 80  # Percentage
    high_cpu_usage_threshold: 90     # Percentage
  
  # Metrics retention
  metrics_retention_hours: 24
  
# Security
security:
  enable_input_validation: true
  max_sequence_length: 1000
  max_batch_size: 1000
  
# Experimental Features
experimental:
  enable_attention_visualization: false
  enable_feature_importance: false
  enable_adversarial_training: false
